# -*- coding: utf-8 -*-
"""Mirror the asset pack into the game, and say exactly what changed.

WHY THIS EXISTS. The pack at `Code Projects\\Coilover-remastered` is generated
and regenerated by Blender and numpy scripts, so it moves under us. Copying by
hand meant two separate occasions of being quietly out of date: first a whole
`endless/` folder that had appeared since the last look, and worse, seven
files that had been SILENTLY REGENERATED after I copied them, including both
flora libraries and the weather module. Those are precisely what the next two
steps of the work order run on, so the bug would not have shown up as a
missing file. It would have shown up as the wrong trees.

So the question "do you have all the assets" is now a command, not a guess:

    python sync-assets.py            report what differs, change nothing
    python sync-assets.py --write    copy the differences in

WHAT IS DELIBERATELY LEFT OUT, and why. These are not oversights, and the
script prints them every run so the decision stays visible:

  height_1m.png            Physics reads the analytic height() functions, and
                           that is the point of them: the terrain maps were
                           sampled FROM those functions, so a height texture
                           would be a second, lower-resolution copy of a thing
                           the game already computes exactly.
  terrain_*_5m.glb         The pack calls these previews, for other tools.
  textures/*_albedo
          *_normal
          *_orh
          *_height16       13 MB of PBR sets. The game's look is a posterised
                           Phong shader with projected grain; it has nowhere
                           to put a normal or roughness map. The grain PNGs
                           from the same folder ARE taken.
"""
import io, os, shutil, filecmp, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = r"C:\Users\Robert Walter-Joseph\Code Projects\Coilover-remastered"
DEST = os.path.join(HERE, 'docs')

WRITE = '--write' in sys.argv

# (source subtree, destination subtree). Whole trees, minus the skips below.
TREES = [
    (os.path.join('assets', 'vehicles'), os.path.join('assets', 'vehicles')),
    (os.path.join('assets', 'props'),    os.path.join('assets', 'props')),
    (os.path.join('assets', 'flora'),    os.path.join('assets', 'flora')),
    (os.path.join('assets', 'bridges'),  os.path.join('assets', 'bridges')),
    (os.path.join('assets', 'roads'),    os.path.join('assets', 'roads')),
    (os.path.join('assets', 'weather'),  os.path.join('assets', 'weather')),
    (os.path.join('assets', 'terrain'),  os.path.join('assets', 'terrain')),
    (os.path.join('assets', 'textures', 'grain'), os.path.join('assets', 'grain')),
    # step 11's reference implementation: worldgen.js is the shared source of
    # truth for the endless world, so the game and its physics agree.
    ('endless', 'endless'),
]

SKIP_NAMES = {'height_1m.png'}
SKIP_SUFFIX = ('_5m.glb', '_albedo.png', '_normal.png', '_orh.png', '_height16.png')
# the endless reference embeds its own copies of models we already ship loose
SKIP_PARTS = (os.path.join('endless', 'assets', 'bracken'),
              os.path.join('endless', 'assets', 'flora_'))

def skipped(rel):
    base = os.path.basename(rel)
    if base in SKIP_NAMES: return 'physics uses the analytic height()'
    for s in SKIP_SUFFIX:
        if base.endswith(s):
            return 'preview mesh' if s == '_5m.glb' else 'PBR map, no shader slot'
    for part in SKIP_PARTS:
        if part in rel: return 'duplicate of an asset already shipped loose'
    return None

added, updated, skipped_n, same = [], [], 0, 0

for src_sub, dst_sub in TREES:
    src_root = os.path.join(PACK, src_sub)
    if not os.path.isdir(src_root):
        print('  (pack has no %s)' % src_sub)
        continue
    for dirpath, _dirs, files in os.walk(src_root):
        for f in files:
            sp = os.path.join(dirpath, f)
            rel = os.path.relpath(sp, src_root)
            why = skipped(os.path.join(src_sub, rel))
            if why:
                skipped_n += 1
                continue
            dp = os.path.join(DEST, dst_sub, rel)
            if not os.path.exists(dp):
                added.append(os.path.join(dst_sub, rel))
            elif not filecmp.cmp(sp, dp, shallow=False):
                updated.append(os.path.join(dst_sub, rel))
            else:
                same += 1
                continue
            if WRITE:
                os.makedirs(os.path.dirname(dp), exist_ok=True)
                shutil.copy2(sp, dp)

print('pack: %s' % PACK)
print('game: %s\n' % DEST)
print('unchanged %d   new %d   STALE %d   left out %d'
      % (same, len(added), len(updated), skipped_n))
for f in updated: print('  stale -> %s' % f)
for f in added:   print('  new   -> %s' % f)
print('\nleft out on purpose: height_1m.png, *_5m.glb previews, PBR map sets'
      ' (see the docstring for why)')
if (added or updated) and not WRITE:
    print('\nnothing was written. run with --write to copy these in.')
elif WRITE and (added or updated):
    print('\ncopied. run `python build.py`, and re-run the sw.js model list if'
          ' the manifest changed.')
